			</div>
		<!-- </div> -->
		<footer  class="footer">
			<div class="copyright">
			<hr>
				<center><p>&copy;<span title="I:4; Q:1; S:1; C:56; F:4; T:238.89; H:com">2014</span><a href="http://waimai.meituan.com/">美团外卖</a> </center>
			</div>
		</footer>
		<!-- 底部导航栏 -->
		 <button  id="goTop">^</button>
	   	<!-- 页面的全局启动脚本文件 start-->
	   <script  data-main="/static/js/page/global" src="/static/js/lib/r.js"></script>
	   
	   <script type="text/script">
	   		require(['global'],function(general){
	   			general(".list-group");
	   		});


	   </script>
	   <!-- 页面的启动脚本文件 end-->
		</body>
		
</html>